# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alt.pathawks.com
production_url: http://alt.pathawks.com
baseurl: /
root: /
title: alt.pathawks.com
# subtitle: A blogging framework for hackers.
author: 
    name:       "Pat Hawks"
    url:        "https://plus.google.com/102057071740749981761?rel=author"
    image:      "http://pathawks.com/images/pat/apple-300.png"
    email:      "pat@pathawks.com"
    twitter:    "pathawks"
    facebook:   "pathawks"
    github:     "pathawks"
    googleplus: "102057071740749981761"

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
# date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.pathawks.com/altfeed
subscribe_email:
# RSS feeds can list your email address if you like
email: pat@pathawks.com

lang: en-US
owner_link:  http://pathawks.com
license:   http://creativecommons.org/licenses/by/3.0/deed.en_US
copyright: http://creativecommons.org/licenses/by/3.0/deed.en_US

timezone: "America/Chicago"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
permalink: /:title.html
# source: source
# destination: public
# plugins: plugins
# code_dir: downloads/code
# category_dir: search/label
# markdown: rdiscount
# lsi: false
pygments: true

exclude:
  - 'Rakefile'
  - 's3_website.yml'
  - 'CNAME'
  - 'Readme.md'

guid: "http://alt.pathawks.com/"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: pathawks
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Fonts
fonts:
  google:
    - 
      name: "Source Sans Pro"
      styles:
        - "400"
        - "700"
        - "400italic"
        - "700italic"
    -
      name: "Source Code Pro"
      styles:
        - "400"
        - "700"
    -
      name: "Play"

audioplayer: "http://media.pathawks.com/audioplayer.swf"  